### ISSUE TITLE
It works locally and fails remotely 

### ISSUE THREAD

**Issue by MotionDesignStudio** [aaronpk/Google-Voice-PHP-API#17]
This is the error I am receiving.

Fatal error: Uncaught exception 'Exception' with message 'Could not log in to Google Voice with username: XXXXX@hotmail.com' in /mnt/stor1-wc2-dfw1/416498/627339/php.mo-de.net/web/content/farse/Google-Voice-PHP-API-master/GoogleVoice.php:69 Stack trace: #0 /mnt/stor1-wc2-dfw1/416498/627339/php.mo-de.net/web/content/farse/Google-Voice-PHP-API-master/GoogleVoice.php(204): GoogleVoice->_logIn() #1 /mnt/stor1-wc2-dfw1/416498/627339/php.mo-de.net/XXX/XXX/XXX/XXXX.php(20): GoogleVoice->getUnreadSMS() #2 {main} thrown in /mnt/stor1-wc2-dfw1/416498/627339/php.mo-de.net/XXX/XXXX/XXXXX/Google-Voice-PHP-API-master/GoogleVoice.php on line 69

**Comment by lindylex** [comment]
Boombatower and DanielMarquad I printed out the html error where exception error is located and this is what I see.  It look like want to me prove what cide I login from.  It is asking me some secirity question.

This is the line I modified to display the error.

"throw new Exception("Could not log in to Google Voice with username: PRINT HTML >> ". print_r($html)." << PRINT HTML". $this->_login);"

May you help me solve this please?  
http://mo-de.net/d/error.png

Sorry for the huge delay.  I was in hosting company hell for 7 months.

**Comment by lindylex** [comment]
[ Solution Solved ]

The problem: Google does not like less secure applications to have access to your account.  When these applications try to login addition verification steps are needed.  A way to get pass this is to decrease the level of security by doing the following.  

-  Log into the account you are tying to use at www.google.com/voice
-  Go here: https://www.google.com/settings/security/lesssecureapps  Where it say "Access for less secure apps" select "Enable".
-  Go here: https://accounts.google.com/DisplayUnlockCaptcha  and click on "Continue". 

That solved it for me.  

Thanks for all the help, until next time.

**Comment by sandhibaljeet** [comment]
hello  DanielMarquard,
i found this today and this is very nice n helpful, but i have some issue with 

Fatal error: Uncaught exception 'Exception' with message 'Could not parse for GALX token' in /home/anjali09/public_html/sms2/GoogleVoice.php:48 Stack trace: #0 /home/anjali09/public_html/sms2/GoogleVoice.php(110): GoogleVoice->_logIn() #1 /home/anjali09/public_html/sms2/example.php(13): GoogleVoice->callNumber('9530519517', '5558675309', 'mobile') #2 {main} thrown in /home/anjali09/public_html/sms2/GoogleVoice.php on line 48
please tell me about this and a solution.

**Comment by marallyn** [comment]
Look at https://github.com/xenth/Google-Voice-PHP-API
It is a forked version of this repository that parses the google login page using a more robust dom method.
Also look at https://github.com/marallyn/Google-Voice-PHP-API
which is a fork of xenth's fork that adds a few more functions and abstractions.

**Comment by DavidBerdik** [comment]
I wrote a script that uses this API set up as a cron job to run once a minute, and while it works for a little while, it seems that after enough login attempts, Google starts throwing captchas in to the mix, which causes trouble logging in. Does anyone have a solution to that, or does change account settings to allow less secure apps fix the problem?

**Comment by daviddietz-zz** [comment]
@DavidBerdik Give this a try:
https://accounts.google.com/b/0/DisplayUnlockCaptcha

**Comment by DavidBerdik** [comment]
@daviddietz-zz I haven't quite figured out what the link does, but I did push the "Continue" button.

**Comment by daviddietz-zz** [comment]
@DavidBerdik 
**Unlock Gmail for a New Email Program or Service:**
To allow a new email program that Gmail has blocked as suspicious access to your account:

**1.** Have the email program or service (cron job) that has failed to access your Gmail account ready.
Important: If you use 2-step authentication with your Gmail account (https://www.lifewire.com/secure-your-gmail-account-with-password-and-phone-authentication-1171958), make sure you create an application password for the new client (https://www.lifewire.com/get-a-password-to-access-gmail-by-pop-imap-2-1171882).

**2.** Visit the Allow access to your Google account page at Google.
(https://accounts.google.com/DisplayUnlockCaptcha)
Note: Log in to the desired Gmail account if prompted.

**3.** Click Continue.

**4.** Within 10 minutes of clicking "Continue," have the previously blocked email service or program (your cron job) check for new messages.

**Comment by DavidBerdik** [comment]
@daviddietz-zz Okay thank you. I had to change my script to use a new Google account, and within the first 24 hours of doing so, I had to use this twice, but since then, it appears to be working without any interruptions.
