### ISSUE TITLE
"May need to change scraping" Error

### ISSUE THREAD

**Issue by DavidBerdik** [aaronpk/Google-Voice-PHP-API#30]
This morning, I started receiving the following error when trying to use this API with my texting script. For privacy, I have stripped out some parts of the error, marking them as "\<REDACTED\>." Note that the "Passwd" entry in the array is empty, and not marked, meaning that the password was never even received (read: I did not remove the password and forget to mark having done so when posting this. It was never there.). Has anyone else started seeing this as well?

```
Could not log in to Google Voice with username: <REDACTED>

May need to change scraping.  Here are the inputs from the page:
array (
  'Page' => 'PasswordSeparationSignIn',
  '' => '',
  'gxf' => '<REDACTED>',
  'continue' => 'https://www.google.com/voice/b/0/redirection/voice',
  'followup' => 'https://www.google.com/voice/b/0/redirection/voice',
  'service' => 'grandcentral',
  'flowName' => 'GlifWebSignIn',
  'ProfileInformation' => '<REDACTED>',
  'SessionState' => '<REDACTED>',
  '_utf8' => '☃',
  'bgresponse' => 'js_disabled',
  'Email' => '<REDACTED>',
  'Passwd' => '',
  'logintoken' => '<REDACTED>',
  'url' => '<REDACTED>',
  'logintoken_audio' => '<REDACTED>',
  'url_audio' => '<REDACTED>',
  'logincaptcha' => '',
  'signIn' => 'Sign in',
  'PersistentCookie' => 'yes',
)
PHP Fatal error:  Uncaught Exception: Could not log in to Google Voice with username: <REDACTED>
Look at error log for detailed input information.
 in /home/<REDACTED>/Desktop/<REDACTED>/GoogleVoice.php:75
Stack trace:
#0 /home/<REDACTED>/Desktop/<REDACTED>/GoogleVoice.php(160): GoogleVoice->_logIn()
#1 /home/<REDACTED>/Desktop/<REDACTED>/texter.php(6): GoogleVoice->sendSMS('<REDACTED>', '<REDACTED>')
#2 {main}
  thrown in /home/<REDACTED>/Desktop/<REDACTED>/GoogleVoice.php on line 75

```

**Comment by programmer007007** [comment]
Did you managed to solve it ?

**Comment by DavidBerdik** [comment]
I did not myself, but I found a forked version that has resolved it: https://github.com/jamenlang/Google-Voice-PHP-API

**Comment by programmer007007** [comment]
Yup even i tried his version but it doesn't seem to work anymore from last few weeks ? . is it still working for you ?

**Comment by DavidBerdik** [comment]
I just tested it and it is indeed working for me. Check that Google is not blocking the sign-in attempt. I have seen that happen before.

**Comment by programmer007007** [comment]
strange . i debugged the curl code & its showing me JavaScript disable error & logging out on further calls .

**Comment by programmer007007** [comment]
And unlike before it doesn't shows that blocked login attempt and ask to authenticate it. so it seems like its stuck on this JavaScript error .

**Comment by DavidBerdik** [comment]
What is the error?

**Comment by programmer007007** [comment]
This is the error that i am receiving and it seems like googles function is doing its jobs as it  should. :smiling_imp: 
https://www.zdnet.com/article/google-wont-let-you-sign-in-if-you-disabled-javascript-in-your-browser/

Now i am in search of what cookies it sets to check this JavaScript status of a browser.

**Comment by DavidBerdik** [comment]
That's kind of odd though. Did you make any code changes?

**Comment by programmer007007** [comment]
nope but yes i did changed my recovery address recently & it seems like it picks up the new policy & applies it to you account i guess this is the new way of google through which they are slowly but forcefully migrating people to the their crappy newer version of every product.

**Comment by DavidBerdik** [comment]
I actually was not aware that they were making such a change.
